INSERT INTO productobd (nombre, precio, cantidad) VALUES('Sérum de SkinCeuticals', 12, 300);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Copas Menstruales derologo', 10, 200);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Proteoglicanos soes', 10, 800);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Crema antiedad miral', 5, 200);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Aceite antiestrías foer', 3, 700);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Agua de Belleza de Caudalie', 5, 500);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Perfumes levon', 10, 700);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Starter Deck', 10, 550);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Pilexel 100 cap', 12, 450);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Farmartint', 10, 700);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Negogenic champu', 10, 900);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Nutraedica anticaspa', 10, 900);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Marti Derm', 12, 500);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Phyto re', 7, 800);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Nopucip anticaspa', 5, 300);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Gel EGO', 10, 600);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Pasta dental', 5, 500);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Condones piel', 8, 600);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Panadol', 10, 700);
INSERT INTO productobd (nombre, precio, cantidad) VALUES('Antalgina', 5, 800);

